<?php

$xml->Complete->OriginDepotID;/** **/
$xml->Complete->LaroseDepotID;//onlyWorld
$xml->Complete->ItemNo;/**/
$xml->Complete->Weight;/**/
$xml->Complete->Volume;
$xml->Complete->ConsignmentNo;
$xml->Complete->CheckDigits;
$xml->Complete->ShipmentKey;
$xml->Complete->Date;
$xml->Complete->WeekEnd;//onlyWorld
$xml->Complete->TNTConNo;/**/
$xml->Complete->SenderName;
$xml->Complete->CustomerRef;/**/
$xml->Complete->AccountNo;
$xml->Complete->SndAddress;
$xml->Complete->SndTown;
$xml->Complete->SndProvince;
$xml->Complete->SndZIPCode;
$xml->Complete->SndCountry;
$xml->Complete->SndContactName;
$xml->Complete->SndPhone;
$xml->Complete->Receiver;
$xml->Complete->Receiver->Name;
$xml->Complete->Receiver->Address;
$xml->Complete->Receiver->Town;
$xml->Complete->Receiver->ZIPCode;
$xml->Complete->Receiver->Country;
$xml->Complete->Receiver->ContactName;
//$xml->Complete->Receiver->Province;
$xml->Complete->Receiver->Phone;
//$xml->Complete->Receiver->Email;
$xml->Complete->DestinationDepot->DepotID;
$xml->Complete->DestinationDepot->DepotName;
$xml->Complete->SenderReference;
$xml->Complete->Service;
$xml->Complete->ServiceCode;//onlyWorld
$xml->Complete->Option;
$xml->Complete->SpecialGoods;
$xml->Complete->GoodsDesc;
$xml->Complete->SpecialInstruction;
$xml->Complete->CODValue;
$xml->Complete->CODCurrency;
$xml->Complete->DestinationHUB;
$xml->Complete->Microzone;
$xml->Complete->OperationalOption;//onlyWorld
$xml->Complete->invoicevalue;//onlyWorld
$xml->Complete->invoicecurrency;//onlyWorld
$xml->Complete->ProductDescription;//onlyWorld**
$xml->Complete->OptionDescription;//onlyWorld**
$xml->Complete->PremiumService;//onlyWorld
$xml->Complete->Reference->ValueCode;//onlyWorld**
$xml->Complete->Delivery->Town;//onlyWorld
$xml->Complete->Delivery->DeliveryZone;//onlyWorld
$xml->Complete->Delivery->DepotActionDate;//onlyWorld**
$xml->Complete->Delivery->PostCode;//onlyWorld
$xml->Complete->Delivery->DepotActionDayWeek;//onlyWorld
$xml->Complete->Sort->LocalHubFromCountry;//onlyWorld
$xml->Complete->Sort->LocalHubFromDepot;//onlyWorld
$xml->Complete->Sort->GateWayCode;//onlyWorld
$xml->Complete->Sort->SortBuildId;//onlyWorld
$xml->Complete->Sort->SortCell;//onlyWorld
$xml->Complete->Sort->SortCellLocation;//onlyWorld
$xml->Complete->Routing->RoutingDescription;//onlyWorld**
$xml->Complete->Routing->SortHazardCode;//onlyWorld**
$xml->Complete->Routing->SortSplitCode;//onlyWorld**
$xml->Complete->Routing->ViaDepot1;//onlyWorld**
$xml->Complete->Routing->ViaDepot2;//onlyWorld**
$xml->Complete->Routing->ViaDepot3;//onlyWorld**
$xml->Complete->Routing->ViaDepot4;//onlyWorld**
$xml->Complete->Destination->Town;//onlyWorld
$xml->Complete->Destination->Depot;//onlyWorld**
$xml->Complete->Destination->LocalHubToDepotDescription;//onlyWorld**
$xml->Complete->Destination->CountryId;//onlyWorld
$xml->Complete->Destination->CountryName;//onlyWorld
$xml->Complete->Destination->ClusterCode;//onlyWorld
$xml->Complete->Destination->LocalHubToDepot;//onlyWorld
$xml->Complete->Destination->ExtraCEE;//onlyWorld
$xml->Complete->Version->VersionApplicationCode;//onlyWorld
$xml->Complete->Version->VersionDate;//onlyWorld
$xml->Complete->Version->VersionMasterfileDate;//onlyWorld
$xml->Complete->Version->VersionTime;//onlyWorld
$xml->Complete->Version->VersionUser;//onlyWorld

$xml->Complete->DivisionDescription;//onlyWorld
$xml->Complete->Sender->Account;//onlyWorld
$xml->Complete->Sender->Name;//onlyWorld
$xml->Complete->Sender->Address;//onlyWorld
$xml->Complete->Sender->Town;//onlyWorld
$xml->Complete->Item->ItemID;
$xml->Complete->Item->ItemIncrNo;
$xml->Complete->Item->Barcode;
$xml->Complete->Item->ItemSequenceNo;/**/
$xml->Complete->Item->ItemWeight;
$xml->Complete->Item->ItemReference;
$xml->Complete->Item->ItemLenght;
$xml->Complete->Item->ItemHeight;
$xml->Complete->Item->ItemWidth;
//$xml->Complete->Item->ItemLenght;
$xml->Complete->Item->ItemType;

